# Generated by Django 3.2.4 on 2021-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField()),
                ('afrom_time', models.TimeField()),
                ('ato_time', models.TimeField()),
            ],
            options={
                'ordering': ['adate'],
                'get_latest_by': 'adate',
            },
        ),
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
            options={
                'db_table': 'Time_Slot',
                'ordering': ['date'],
                'get_latest_by': 'date',
            },
        ),
    ]
